name: Stock Alert

on:
  schedule:
    - cron: "30 0 * * *"   # 10:30 AM Sydney
    - cron: "0 3 * * *"    # 1:00 PM Sydney
    - cron: "30 6 * * *"   # 4:30 PM Sydney
    - cron: "20 10 * * *"   # 8:20 PM Sydney
  workflow_dispatch:        # allows manual run in GitHub

jobs:
  run-stock-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install yfinance

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python stock_alert.py

